### ISSUE TITLE
Real thermostat don't update

### ISSUE THREAD

**Issue by sdomotica** [nepotu/ohscheduler#6]
I set you widget, everythings works well.
If set I manually the setpoint the widget set correctly the setpoint.
But, when run the scheduler the widget show rightly, I have on events.log the right new setpoint, but OpenHab2 don't send the new setpoint to real thermostat (mqtt).
Very strange

**Comment by nepotu** [comment]
Hello Sandro! I am afraid this has nothing to do with the widget. If the values (set points) are updated then you should check the rules that control the "hardware thermostat" (you should have a rule that triggers the change on the "hardware thermostat" once the set point is updated).

**Comment by sdomotica** [comment]
Hi, thank you so much for quick answer. I'm looking on your rules for change the logic. Don't update the items but send mqtt message for set the setpoint. I think is an Openhab2 issue. I wrote here for keep update you. Your job it's very great.
