### ISSUE TITLE
Not switching 

### ISSUE THREAD

**Issue by Shalvan** [nepotu/ohscheduler#7]
Hi there, 

First of all I would like to thank You for a great job :) Second, i am new to OpenHab (thinking of port form Node-red).
So now, i would like to use Your widget to control light but nothing is happening and i am getting error in the openhabs console:

> 2018-11-04 20:37:00.579 [INFO ] [ome.model.script.onoff-control.rules] - OnOff Appliances control error: java.lang.ArrayIndexOutOfBoundsException: 1 
> 2018-11-04 20:38:00.500 [INFO ] [ome.model.script.onoff-control.rules] - OnOff Appliances control error: java.lang.ArrayIndexOutOfBoundsException: 1

and its keep going every minute

te config looks like this:

Scheduler Type - On/Off
Schedule Store Item - OnOff_Schedule
Items - [{"setItem":"OnOff_SP_Coffee","label":"Coffee SP"}]
Running Mode Item - OnOff_Mode

What can be wrong ?
If You would like i can write additional info.. but i need to know what to write.

With regards 
Lukas

**Comment by nepotu** [comment]
Hello Lukas,

From the looks of it you don't have a schedule set up, hence the OpenHAB rule fails while parsing the item which should contain the schedule.

Kind regards,
Geo
