### ISSUE TITLE
Thermostat Switch item

### ISSUE THREAD

**Issue by andrea-daru** [nepotu/ohscheduler#9]
I can't find documentation or example to configure the Thermostat switch item.
I want to switch on a relay when the target temp it's not already reached.

**Habpanel widget "Items" config**
`[{"setItem": "HVAC_Sala_Target_Temp", "label": "Termostato sala", "readItem": "HVAC_Sala_Temp", "switchItem": "ValvolaSala"}]`

> HVAC_Sala_Target_Temp -> room target temp
> HVAC_Sala_Temp -> Room current temp
> ValvolaSala -> Relay to switch on

Thank you in advance!

**Comment by nepotu** [comment]
This widget provides the scheduling part (change the target temperature at a given moment), which was missing on OH. The way you control your relays is independent of this widget and are out of scope.

HINT: you should create additional items and rules for your relays.

**Comment by andrea-daru** [comment]
Thank you for the response!
